# Generated by Django 5.0.6 on 2024-06-17 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200)),
                ('model_year', models.CharField(max_length=4)),
                ('plate', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('finished_at', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('status', models.CharField(choices=[('O', 'OPEN'), ('F', 'FINISHED'), ('C', 'CANCELED')], max_length=1)),
                ('comments', models.TextField(blank=True, max_length=1000, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand', to='service_orders.brand')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to='customers.client')),
            ],
        ),
    ]
