# Generated by Django 5.0.6 on 2024-06-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0002_serviceorder_products_serviceorder_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='client',
            field=models.CharField(max_length=500),
        ),
    ]
