# Generated by Django 5.0.6 on 2024-06-20 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('service_orders', '0004_serviceorder_phone1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client'),
        ),
    ]
