# Generated by Django 5.0.6 on 2024-07-01 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('service_orders', '0005_alter_serviceorder_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.client'),
        ),
    ]
