# Generated by Django 5.0.6 on 2024-07-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0006_alter_serviceorder_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
