# Generated by Django 5.0.6 on 2024-06-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('estimated_time', models.IntegerField(blank=True, default=0, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
