# Generated by Django 5.0.6 on 2024-06-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('address_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone1', models.CharField(max_length=15)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
